-- Seed: Populate gestures table with data from table.csv, including image_path and boolean canupgradetomajor

insert into gestures (name, description, minor_major, canupgradetomajor, penaltytime, isstickpenalty, image_path) values
('Cambio ilegal','Más de 4 en pista o cambio antes de 3 m del banquillo. Si es deliberado en los 2 últimos minutos, penalti.','minor',true,2,false,'6_en_pista.png'),
('Agarrar','Sujetar a un rival e impedir su movimiento. Puede sancionarse con mala conducta.','minor',true,2,false,'agarrar.png'),
('Cambio','El equipo visitante tiene cinco segundos para realizar el cambio. El equipo local dispone de cinco segundos más.','none',false,0,false,'cambio.png'),
('Carga','Embestir a un rival corriendo, saltando o empujando con el cuerpo. Si es peligrosa o causa lesión, puede ser mayor.','minor',true,2,false,'carga.png'),
('Carga con el stick','Empujar a un rival con el stick. A la tercera sanción de stick: expulsión.','minor',true,2,true,'carga_con_stick.png'),
('Carga por la espalda','Cargar por la espalda a un rival. Si hay lesión, expulsión.','minor',true,2,false,'carga_por_detras.png'),
('Codazo','Uso del codo para golpear a un adversario. Si causa lesión, expulsión.','minor',true,2,false,'codazo.png'),
('Conducta antideportiva','Conducta antideportiva o retraso. Reincidencia: expulsión. El portero cruza medio campo o mueve la portería al final.','major',false,10,false,'antideportiva.png'),
('Enganchar','Sujetar con el stick al adversario para impedirle avanzar. Si hay lesión, expulsión.','minor',true,2,true,'enganche.png'),
('Gol','Se cancela la primera penalización menor del equipo que recibe el gol. Si la penalización es mayor o de mala conducta, no se cancela.','none',false,0,false,'gol.png'),
('Golpear con el taco','Golpear con el taco del stick. A la tercera sanción de stick: expulsión.','major',false,5,true,'golpear_taco.png'),
('Golpear punta del stick','Golpear con la punta del stick. Si hay lesión, penalización de partido. A la tercera sanción de stick: expulsión.','minor',true,4,true,'golpear_stick.png'),
('Penalización de partido','El jugador es expulsado el resto del encuentro por infracción grave, acumulación de faltas o mala conducta.','major',false,5,false,'penalizacion_de_partido.png'),
('Penalización diferida','El juego sigue hasta que el equipo infractor recupere el puck.','none',false,0,false,'diferida.png'),
('Interferencia','Obstaculizar a un rival sin posesión del puck. Si provoca lesión, expulsión.','minor',true,2,false,'interferencia.png'),
('Jugador en el área','Si un atacante entra sin puck o sin ser empujado por un defensor, el juego se detiene y el saque neutral se realiza en el centro de la pista.','none',false,0,false,'area.png'),
('Mala conducta','Lenguaje, gestos o protestas reiteradas. Se le sustituye, así que no deja al equipo en inferioridad.','major',false,10,false,'mala_conducta.png'),
('No gol, no falta','Ante una situación confusa el árbitro señala que no hay gol o no hay falta.','none',false,0,false,'no_gol.png'),
('Pase con la mano','Saque neutral en el centro si el pase con la mano fue en zona de ataque o en la zona más cercana si ocurrió en defensa.','none',false,0,false,'pase_con_la_mano.png'),
('Rodillazo','Uso de la rodilla para derribar o golpear al rival. Si hay lesión, expulsión.','minor',true,2,false,'rodillazo.png'),
('Slashing','Golpear o intentar golpear con el stick. Si hay lesión, expulsión.','minor',true,2,true,'slashing.png'),
('Stick alto','Usar el stick por encima de los hombros y tocar o poner en peligro a un rival. Si hay lesión, expulsión.','minor',true,2,true,'stick_alto.png'),
('Tiro de penalti','El jugador designado avanza desde el centro y tira. Tras el tiro: saque en el centro.','none',false,0,false,'penalti.png'),
('Violencia innecesaria','Golpes o choques demasiado fuertes sin necesidad. Si hay lesión, expulsión.','minor',true,2,false,'violencia_innecesaria.png'),
('Zancadilla','Hacer tropezar a un rival con stick, pie o cuerpo. Si hay lesión, expulsión.','minor',true,2,true,'zancadilla.png'),
('Tiempo Muerto','Solo lo puede solicitar el capitán, los asistentes o el entrenador.','none',false,3,false,'tiempo.png')
on conflict (name) do update set
  description = excluded.description,
  minor_major = excluded.minor_major,
  canupgradetomajor = excluded.canupgradetomajor,
  penaltytime = excluded.penaltytime,
  isstickpenalty = excluded.isstickpenalty,
  image_path = excluded.image_path;